title: <p align="center"> Yash Joshi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/iyashjoshi/">LinkedIn</a> |
  <a href="https://github.com/Yash-Joshi">GitHub</a>
  
  <br>   
  I'm .net developer, learning Data Science and Machine Learning 
  <br>
  </p>



theme: jekyll-theme-minimal
