title: <p align="center"> Yash Joshi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  
  <br>   
  I'm .net developer, learning Data Science and Machine Learning 
  <br>
  </p>



theme: jekyll-theme-minimal
