title: Yash Joshi
logo: /assets/img/myImage.jpeg

description:
  <p> 
  <p align="center">|
  <a href="https://www.linkedin.com/in/iyashjoshi/">LinkedIn</a> |
  <a href="https://github.com/Yash-Joshi">GitHub</a>
  I'm .net developer, learning Data Science and Machine Learning 
  </p>

theme: jekyll-theme-minimal
